import * as tf from "@tensorflow/tfjs-node";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ============================================
// STEP 1 — LOAD THE JSON FILES WE SAVED
// ============================================
// these were generated by preprocess.ts
// they tell us which index = which symptom/disease

const symptom_list: string[] = JSON.parse(
  fs.readFileSync(path.join(__dirname, "symptom_list.json"), "utf8"),
);

const disease_list: string[] = JSON.parse(
  fs.readFileSync(path.join(__dirname, "disease_list.json"), "utf8"),
);

const severity_map: Record<string, number> = JSON.parse(
  fs.readFileSync(path.join(__dirname, "severity_map.json"), "utf8"),
);

const description_map: Record<string, string> = JSON.parse(
  fs.readFileSync(path.join(__dirname, "description_map.json"), "utf8"),
);

const precaution_map: Record<string, string[]> = JSON.parse(
  fs.readFileSync(path.join(__dirname, "precaution_map.json"), "utf8"),
);

// ============================================
// STEP 2 — LOAD THE TRAINED MODEL
// ============================================
// model is null at start
// load_model() must be called once when server starts
// then it stays in memory for all predictions

let model: tf.LayersModel | null = null;

export const load_model = async () => {
  const model_path = `file://${path.join(__dirname, "saved_model/model.json")}`;
  model = await tf.loadLayersModel(model_path);
  console.log("tensorflow model loaded");
};

// ============================================
// STEP 3 — CONVERT SYMPTOMS TO VECTOR
// ============================================
// same logic as preprocess.ts
// patient symptoms → array of numbers

const symptoms_to_vector = (patient_symptoms: string[]): number[] => {
  // start with 131 zeros
  const vector = new Array(symptom_list.length).fill(0);

  patient_symptoms.forEach((symptom) => {
    // clean the symptom name same way preprocess did
    const cleaned = symptom.trim().toLowerCase().replace(/ /g, "_");

    // find its position in symptom_list
    const index = symptom_list.indexOf(cleaned);

    if (index === -1) {
      // symptom not found in our list
      // this happens when gemini maps to a name not in dataset
      console.warn(`symptom not found in list: ${cleaned}`);
      return;
    }

    // put severity weight at that position
    const weight = severity_map[cleaned] || 1;
    vector[index] = weight;
  });

  return vector;
};

// ============================================
// STEP 4 — PREDICT DISEASE
// ============================================

export type PredictionResult = {
  disease: string;
  confidence: number;
  percentage: string;
  description: string;
  precautions: string[];
};

export const predict_disease = (
  patient_symptoms: string[],
): PredictionResult[] => {
  if (!model) {
    throw new Error("model not loaded — call load_model() first");
  }

  // convert symptoms to vector
  const vector = symptoms_to_vector(patient_symptoms);

  // wrap in another array because tensor2d expects [[...]] not [...]
  // model expects shape [1, 131] — 1 patient, 131 symptoms
  const input_tensor = tf.tensor2d([vector]);

  // run prediction
  // output is shape [1, 41] — 1 patient, 41 disease probabilities
  const output_tensor = model.predict(input_tensor) as tf.Tensor;

  // extract the 41 probabilities as a plain JS array
  const probabilities = Array.from(output_tensor.dataSync());

  // free memory immediately after use
  input_tensor.dispose();
  output_tensor.dispose();

  // pair each probability with its disease name
  const results = disease_list
    .map((disease, index) => ({
      disease,
      confidence: probabilities[index],
      percentage: `${(probabilities[index] * 100).toFixed(1)}%`,
      description: description_map[disease] || "No description available",
      precautions: precaution_map[disease] || [],
    }))
    // sort by confidence — highest first
    .sort((a, b) => b.confidence - a.confidence)
    // return top 3 most likely diseases
    .slice(0, 3);

  return results;
};
